### PR TITLE
Fix inspect keyboard shortcuts and add build.sh

### PR DESCRIPTION
**Pull request by michaeleldar**
There was a big merge conflict on my branch (that also explains all the extra commits), but I was checking the ctrl+r reload shortcut was still there then I noticed the broken inspect element keyboard shortcut. So I fixed it and tested it.

I also added a build.sh file to make building platinum quicker.

I also changed the README a bit to accommodate the build.sh file, so make sure to add that too.

### CODE REVIEW

**Comment by jdev082** [comment]
No need for a build.sh for what, 2 commands...?

**Comment by michaeleldar** [comment]
> No need for a build.sh for what, 2 commands...?

Well it's still pretty useful for me and maybe other people, and what harm does it do?

**Comment by jdev082** [comment]
> > No need for a build.sh for what, 2 commands...?
> 
> Well it's still pretty useful for me and maybe other people, and what harm does it do?

There's no point, just run `npm install` and `npm run make` pretty simple no need for a script.

**Comment by michaeleldar** [comment]
> > > No need for a build.sh for what, 2 commands...?
> > 
> > 
> > Well it's still pretty useful for me and maybe other people, and what harm does it do?
> 
> There's no point, just run `npm install` and `npm run make` pretty simple no need for a script.
And `npm run tailwind:once`

When your multitasking like I sometimes do, it's much easier not to have to run the commands separately.

**Comment by redstone-dev** [comment]
> > > > No need for a build.sh for what, 2 commands...?
> > > 
> > > 
> > > Well it's still pretty useful for me and maybe other people, and what harm does it do?
> > 
> > 
> > There's no point, just run `npm install` and `npm run make` pretty simple no need for a script.
> > And `npm run tailwind:once`
> 
> When your multitasking like I sometimes do, it's much easier not to have to run the commands separately.

Could also be useful if new things get added that require their own build steps: just add it to `build.sh`!

Also, I did not implement the inspect element shortcut; I just left it as `TODO` in the code. Thanks for doing it though!

I will merge this PR...
### _RIGHT NOW!_

**Comment by michaeleldar** [comment]
By the way, it has the about this fork section in the README which you should probably delete.

**Comment by redstone-dev** [comment]
> By the way, it has the about this fork section in the README which you should probably delete.

Fixed

**Pull request merged**
